# Generated by Django 5.0.1 on 2024-02-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['nome']},
        ),
    ]
