# Generated by Django 5.0.1 on 2024-02-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_alter_contacto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='contactos/fotos/'),
        ),
    ]
