# Generated by Django 5.0.1 on 2024-01-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='name',
            new_name='nome',
        ),
    ]
