# Generated by Django 5.0.1 on 2024-01-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0002_rename_name_tarefa_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='completo',
            new_name='concluido',
        ),
    ]
