# Generated by Django 5.0.1 on 2024-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=252)),
                ('quantidade', models.CharField(default='1', max_length=20)),
                ('urgente', models.CharField(choices=[('U', 'Urgente'), ('N', 'Não Urgente')], default='N', max_length=1)),
            ],
        ),
    ]
